# Generated by Django 4.2.7 on 2023-12-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedpet',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='boughtpet',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
