# Generated by Django 4.2.7 on 2023-12-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0002_alter_bookedpet_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedpet',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_pets', to='zoo_app.pet'),
        ),
        migrations.AlterField(
            model_name='boughtpet',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_pets', to='zoo_app.pet'),
        ),
    ]
